# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dhan V Sagar
title: Senior Software Engineer
email: dhanvsagar@gmail.com
website: www.dhanvsagar.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: dhanvsagar
github_username:  dhanvsagar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: dvsagar007
linkedin_username: dhan-v-sagar
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/dvs.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello 👋 I’m Dhan V Sagar. 
  
  I live in Waterloo, Ontario, Canada. 
  
  Accomplished Cloud and Site Reliability Engineer with over 10 years of experience in Cloud Native technologies, DevOps, and Observability. Expertise in infrastructure automation, Kubernetes administration, and cloud operations across AWS, Terraform, and Helm. Proficient in CI/CD, GitOps practices, and monitoring solutions like Prometheus, OpenTelemetry, LGTM Stack and Grafana. Passionate about delivering scalable, reliable, and efficient cloud platforms.

  I have also got a chance to work on some <mark>IPTV/OTT/Video products</mark> in my previous company Nokia Corporation.
  
  As a hobby during my free time, I enjoy capturing landscapes and telling stories through my photography
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cisco Systems
        link: cisco.com
        # link_text: boringcompany.com
        sub_title: Software Engineer IV
        caption: October 2022 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Architected and implemented Metrics 2.0 solutions, enabling Observability as a Service using Prometheus, Grafana Mimir, and Grafana.

            - Migrated 35M active metric series from legacy systems (Circonus, InfluxDB) to Prometheus/Mimir with zero downtime.

            - Led the modernization of logging and observability systems for enhanced service reliability.

            - Deployed and maintained scalable Kubernetes applications using Helm and Terraform.

            - Automated CI/CD pipelines with GitOps tools like ArgoCD and Terraform Enterprise.

            - Conducted incident management and post-mortem analysis to improve system reliability.

            - Created proof-of-concepts (PoCs) for building intelligent agents using LangChain, RAG (Retrieval-Augmented Generation), and integrating internal documentation to enhance team productivity.

            - Modernized infrastructure monitoring using OpenTelemetry (OTel).

            - Explored and architected distributed tracing solutions with OpenTelemetry and Tempo.

            - Designed specific logging use cases leveraging Apache Iceberg, Apache Pinot, and AWS Glue for advanced analytics.
      - layout: left
        title: Nokia
        link: nokia.com
        # link_text: boringcompany.com
        sub_title: Technical Lead
        caption: June 2015 - October 2020
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            IPTV/OTT Products
      - layout: left
        title: Alcatel-Lucent
        link: nokia.com
        # link_text: boringcompany.com
        sub_title: Software Engineer - Intern
        caption: December 2014 - June 2015
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            IPTV/OTT Products

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amrita University
        caption: 2013 - 2015
        sub_title: M.Tech Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not working, I like to engage in photography as a way to relax and enjoy my free time. Feel free to checkout them :)
      - [500px](https://500px.com/p/dhanvsagar?view=photos)
      - [Instagram](https://www.instagram.com/dvsagar007/)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
